{
  "comments": [
    {
      "key": {
        "uuid": "70fbe7bf_a923f8f4",
        "filename": "wmfmariadbpy/transfer.py",
        "patchSetId": 1
      },
      "lineNbr": 274,
      "author": {
        "id": 2556
      },
      "writtenOn": "2018-07-27T12:20:50Z",
      "side": 1,
      "message": "In theory you are right that this should be an error and not a warning, but apparently, because how size is calculated, it can differ between source and transfer because how it is calculated. I need to check why, it only happens on large transfers (but the transfer, due to checksums, is ok).",
      "revId": "f89db03f93b54072298b20a2b8f1aea99a4b1239",
      "serverId": "e9e9afe9-4712-486d-8885-f54b72dd1951",
      "unresolved": false
    }
  ]
}